{'objectIdFieldName': 'OBJECTID',
 'uniqueIdField': {'name': 'OBJECTID', 'isSystemMaintained': True},
 'globalIdFieldName': 'GlobalID',
 'geometryType': 'esriGeometryPoint',
 'spatialReference': {'wkid': 4326, 'latestWkid': 4326},
 'fields': [{'name': 'OBJECTID',
   'type': 'esriFieldTypeOID',
   'alias': 'OBJECTID',
   'sqlType': 'sqlTypeOther',
   'domain': None,
   'defaultValue': None},
  {'name': 'incident_number',
   'type': 'esriFieldTypeString',
   'alias': 'Incident Number',
   'sqlType': 'sqlTypeOther',
   'length': 20,
   'domain': None,
   'defaultValue': None},
  {'name': 'incident_type',
   'type': 'esriFieldTypeSingle',
   'alias': 'Incident Type',
   'sqlType': 'sqlTypeOther',
   'domain': None,
   'defaultValue': None},
  {'name': 'incident_type_description',
   'type': 'esriFieldTypeString',
   'alias': 'Incident Description',
   'sqlType': 'sqlTypeOther',
   'length': 100,
   'domain': None,
   'defaultValue': None},
  {'name': 'arrive_date_time',
   'type': 'esriFieldTypeDate',
   'alias': 'Arrival Date',
   'sqlType': 'sqlTypeOther',
   'length': 8,
   'domain': None,
   'defaultValue': None},
  {'name': 'dispatch_date_time',
   'type': 'esriFieldTypeDate',
   'alias': 'Dispatch Date',
   'sqlType': 'sqlTypeOther',
   'length': 8,
   'domain': None,
   'defaultValue': None},
  {'name': 'exposure',
   'type': 'esriFieldTypeInteger',
   'alias': 'Exposure',
   'sqlType': 'sqlTypeOther',
   'domain': None,
   'defaultValue': None},
  {'name': 'platoon',
   'type': 'esriFieldTypeString',
   'alias': 'Platoon',
   'sqlType': 'sqlTypeOther',
   'length': 10,
   'domain': None,
   'defaultValue': None},
  {'name': 'station',
   'type': 'esriFieldTypeInteger',
   'alias': 'Station',
   'sqlType': 'sqlTypeOther',
   'domain': None,
   'defaultValue': None},
  {'name': 'address',
   'type': 'esriFieldTypeString',
   'alias': 'Address',
   'sqlType': 'sqlTypeOther',
   'length': 200,
   'domain': None,
   'defaultValue': None},
  {'name': 'address2',
   'type': 'esriFieldTypeString',
   'alias': 'Secondary Address',
   'sqlType': 'sqlTypeOther',
   'length': 200,
   'domain': None,
   'defaultValue': None},
  {'name': 'apt_room',
   'type': 'esriFieldTypeString',
   'alias': 'Apartment/Room',
   'sqlType': 'sqlTypeOther',
   'length': 254,
   'domain': None,
   'defaultValue': None},
  {'name': 'GlobalID',
   'type': 'esriFieldTypeGlobalID',
   'alias': 'GlobalID',
   'sqlType': 'sqlTypeOther',
   'length': 38,
   'domain': None,
   'defaultValue': None},
  {'name': 'cleared_date_time',
   'type': 'esriFieldTypeDate',
   'alias': 'Cleared Date',
   'sqlType': 'sqlTypeOther',
   'length': 8,
   'domain': None,
   'defaultValue': None}],
 'exceededTransferLimit': True,
 'features': [{'attributes': {'OBJECTID': 474765,
    'incident_number': '07-0031665',
    'incident_type': None,
    'incident_type_description': 'NULL',
    'arrive_date_time': 1195125420000,
    'dispatch_date_time': 1195125000000,
    'exposure': 0,
    'platoon': ' ',
    'station': None,
    'address': '6647 LAKE HILL DR RALEIGH, NC 27601',
    'address2': '',
    'apt_room': '0',
    'GlobalID': '5c2e9c89-78d7-4348-bd95-23a69f4039aa',
    'cleared_date_time': 1195125900000},
   'geometry': {'x': -78.62660452385826, 'y': 35.870212857675455}},
  {'attributes': {'OBJECTID': 474766,
